package com.mulesoft.summit.adm;

import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

import org.springframework.core.io.Resource;
import org.springframework.core.io.support.PathMatchingResourcePatternResolver;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2012-09-01T12:10:19.573-03:00
 * Generated source version: 2.5.1
 * 
 */
@WebServiceClient(name = "HospitalInformationService", 
                  wsdlLocation = "file:/file:/Users/nialdarbey/git/Hospital Admissions/hospital_admissions_3/src/main/resources/HospitalInformationService.wsdl",
                  targetNamespace = "http://www.mule-health.com/HospitalInformation/") 
public class HospitalInformationService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.mule-health.com/HospitalInformation/", "HospitalInformationService");
    public final static QName HospitalInformationSOAP = new QName("http://www.mule-health.com/HospitalInformation/", "HospitalInformationSOAP");
    static {
        URL url = null;
        try {
			Resource[] resources = new PathMatchingResourcePatternResolver().getResources("classpath:/HospitalInformationService.wsdl");
			if (resources.length > 0) {
				url = resources[0].getURL();
			}
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
        WSDL_LOCATION = url;
    }

    public HospitalInformationService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HospitalInformationService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HospitalInformationService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns HospitalInformationService
     */
    @WebEndpoint(name = "HospitalInformationSOAP")
    public HospitalInformationService getHospitalInformationSOAP() {
        return super.getPort(HospitalInformationSOAP, HospitalInformationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HospitalInformationService
     */
    @WebEndpoint(name = "HospitalInformationSOAP")
    public HospitalInformationService getHospitalInformationSOAP(WebServiceFeature... features) {
        return super.getPort(HospitalInformationSOAP, HospitalInformationService.class, features);
    }

}
