
package com.mulesoft.summit.adm;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2012-09-01T12:10:19.554-03:00
 * Generated source version: 2.5.1
 * 
 */
public final class HospitalInformationService_HospitalInformationSOAP_Client {

    private static final QName SERVICE_NAME = new QName("http://www.mule-health.com/HospitalInformation/", "HospitalInformationService");

    private HospitalInformationService_HospitalInformationSOAP_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = HospitalInformationService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        HospitalInformationService_Service ss = new HospitalInformationService_Service(wsdlURL, SERVICE_NAME);
        HospitalInformationService port = ss.getHospitalInformationSOAP();  
        
        {
        System.out.println("Invoking admit...");
        com.mulesoft.summit.adm.AdmissionRequest _admit_admissionRequest = null;
        com.mulesoft.summit.adm.AdmissionResponse _admit__return = port.admit(_admit_admissionRequest);
        System.out.println("admit.result=" + _admit__return);


        }

        System.exit(0);
    }

}
