package com.mulesoft.summit.ins;

import java.io.IOException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import org.springframework.core.io.Resource;
import org.springframework.core.io.support.PathMatchingResourcePatternResolver;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2012-09-01T11:43:47.558-03:00
 * Generated source version: 2.5.1
 * 
 */
@WebServiceClient(name = "InsuranceService", 
                  targetNamespace = "http://www.mule-insurance.com/Insurance/") 
public class InsuranceService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.mule-insurance.com/Insurance/", "InsuranceService");
    public final static QName InsuranceSOAP = new QName("http://www.mule-insurance.com/Insurance/", "InsuranceSOAP");
    static {
   	 URL url = null;
        try {
			Resource[] resources = new PathMatchingResourcePatternResolver().getResources("classpath:/InsuranceService.wsdl");
			if (resources.length > 0) {
				url = resources[0].getURL();
			}
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
       WSDL_LOCATION = url;
   }

    public InsuranceService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public InsuranceService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InsuranceService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns InsuranceService
     */
    @WebEndpoint(name = "InsuranceSOAP")
    public InsuranceService getInsuranceSOAP() {
        return super.getPort(InsuranceSOAP, InsuranceService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InsuranceService
     */
    @WebEndpoint(name = "InsuranceSOAP")
    public InsuranceService getInsuranceSOAP(WebServiceFeature... features) {
        return super.getPort(InsuranceSOAP, InsuranceService.class, features);
    }

}
