
package com.mulesoft.summit.ins;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2012-09-01T11:43:47.542-03:00
 * Generated source version: 2.5.1
 * 
 */
public final class InsuranceService_InsuranceSOAP_Client {

    private static final QName SERVICE_NAME = new QName("http://www.mule-insurance.com/Insurance/", "InsuranceService");

    private InsuranceService_InsuranceSOAP_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = InsuranceService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        InsuranceService_Service ss = new InsuranceService_Service(wsdlURL, SERVICE_NAME);
        InsuranceService port = ss.getInsuranceSOAP();  
        
        {
        System.out.println("Invoking verify...");
        com.mulesoft.summit.ins.HospitalCoverRequest _verify_hospitalCoverRequest = null;
        com.mulesoft.summit.ins.HospitalCoverResponse _verify__return = port.verify(_verify_hospitalCoverRequest);
        System.out.println("verify.result=" + _verify__return);


        }

        System.exit(0);
    }

}
